version: '3.8'

services:
  bot:
    build: .
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - ./src:/src/bot/src
      - ./public:/src/bot/public
      - ./logs:/src/bot/logs